GRANT CONNECT ON DATABASE "QuickDrop DW" TO "QuickDropOwner";

\c "QuickDrop DW"

GRANT USAGE, CREATE ON SCHEMA public TO "QuickDropOwner";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "QuickDropOwner";
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO "QuickDropOwner";

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "QuickDropOwner";

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO "QuickDropOwner";
